name: jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - statsmodels
  - scikit-learn
  - statannotations
  - scikit-posthocs
  - papermill
  - umap-learn
  - pingouin
prefix: /home/mattiazzilab/.conda/envs/jupyter
#conda env export --from-history > environment.yml